# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daa555515534650d22aca7d0d97b3492039b83833259a1e2911cf94564d310e2fc31886e1db5bdaccbfb6a60ab17ac772fd6b0da055749fcd6fea30ef7ef9a59

test:
  secret_key_base: 0dddec3b7340366b132d3571ffa7c8fb31cd30100773bdb841b1b97bd444c3c2fb55e7ef198b86655e499ea41b926430d80a6abfb2e8cb9b5fbde74212f1538e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
